import 'package:flutter/material.dart';
import '../equipment_model.dart';

class BackpacksData {
  static const List<EquipmentSubCategory> categories = [
    EquipmentSubCategory(
      id: 'bp_daypack',
      title: 'Day Pack (15–30 L)',
      subtitle: 'Ideal for single-day hikes and short outings.',
      icon: Icons.backpack_outlined,
      color: Color(0xFF1A7A6E),
      bgColor: Color(0xFFE0F2F1),
    ),
    EquipmentSubCategory(
      id: 'bp_weekend',
      title: 'Weekend Pack (30–50 L)',
      subtitle: 'Perfect for 1–3 night camping trips.',
      icon: Icons.hiking_outlined,
      color: Color(0xFF2D6A4F),
      bgColor: Color(0xFFE8F5E9),
    ),
    EquipmentSubCategory(
      id: 'bp_multiday',
      title: 'Multi-Day Pack (50–70 L)',
      subtitle: 'Built for 3–7 day wilderness expeditions.',
      icon: Icons.terrain_outlined,
      color: Color(0xFF1565C0),
      bgColor: Color(0xFFE3F2FD),
    ),
    EquipmentSubCategory(
      id: 'bp_expedition',
      title: 'Expedition Pack (70 L+)',
      subtitle: 'Heavy-duty packs for extended high-altitude trips.',
      icon: Icons.landscape_outlined,
      color: Color(0xFF6A1B9A),
      bgColor: Color(0xFFF3E5F5),
    ),
    EquipmentSubCategory(
      id: 'bp_hydration',
      title: 'Hydration Pack',
      subtitle: 'Hands-free water delivery for trail running & cycling.',
      icon: Icons.water_drop_outlined,
      color: Color(0xFF0277BD),
      bgColor: Color(0xFFE1F5FE),
    ),
    EquipmentSubCategory(
      id: 'bp_kids',
      title: "Children's Pack",
      subtitle: 'Lightweight packs sized and fitted for young hikers.',
      icon: Icons.child_care_outlined,
      color: Color(0xFFF57F17),
      bgColor: Color(0xFFFFF3E0),
    ),
  ];

  static const List<EquipmentGuide> guides = [
    EquipmentGuide(
      id: 'bp_daypack_guide',
      subCategoryId: 'bp_daypack',
      title: 'Day Pack Packing Guide',
      description:
          'A day pack (15–30 L) is your essential companion for single-day hikes, nature walks, and casual outings. '
          'A properly packed day pack keeps you comfortable, safe, and well-hydrated without weighing you down. '
          'Focus on lightweight, multi-purpose items and always carry the "Ten Essentials" for day hiking.',
      essentialItems: [
        'Water (minimum 2 litres — 500 ml per hour of hiking)',
        'Trail snacks / high-energy food (nuts, bars, dried fruit)',
        'Navigation (trail map + compass, or GPS device)',
        'First aid kit (blister care, bandages, antiseptic)',
        'Headlamp with fresh batteries',
        'Emergency whistle',
        'Sunscreen SPF 30+ and UV sunglasses',
        'Rain jacket or waterproof layer',
        'Mobile phone (fully charged)',
        'Emergency cash and ID',
      ],
      niceToHaveItems: [
        'Lightweight trekking poles',
        'Insulating mid-layer (fleece or down vest)',
        'Insect repellent',
        'Small camera or action camera',
        'Portable power bank',
        'Pack rain cover',
        'Trekking gaiters (for wet or muddy trails)',
      ],
      buyingTips: [
        'Try the pack on with a loaded weight — look for padded shoulder straps and an adjustable sternum strap.',
        'A hip belt on a day pack is only useful if the pack will carry more than 5 kg; skip it for lightweight use.',
        'Hydration sleeve compatibility is a plus — allows a water bladder without taking up main compartment space.',
        'Multiple external pockets let you keep frequently accessed items (snacks, phone, sunscreen) within reach.',
        'Durable water repellent (DWR) coating on the outer fabric provides light rain resistance without adding weight.',
      ],
      careTips: [
        'Empty and air-dry the pack completely after every use to prevent mildew forming in damp fabric.',
        'Wipe the inside with a damp cloth monthly; use mild soap only — never machine-wash unless the label permits.',
        'Store your pack loosely stuffed (not compressed flat) to maintain the shape of the shoulder straps.',
        'Lubricate zippers with a dry zipper wax twice per season to prevent sticking and corrosion.',
        'Check all buckles, strap anchors, and seams regularly — field-repair minor fraying before it becomes a failure.',
      ],
    ),
    EquipmentGuide(
      id: 'bp_weekend_guide',
      subCategoryId: 'bp_weekend',
      title: 'Weekend Pack Packing Guide',
      description:
          'A 30–50 L weekend pack is the workhorse of casual camping — large enough to carry overnight gear without '
          'the bulk of a full expedition pack. Proper organisation, weight distribution, and carrying all ten essentials '
          'makes the difference between a comfortable trip and a punishing one.',
      essentialItems: [
        'Sleeping bag appropriate for the season (rated to at least 5°C below expected low)',
        'Sleeping pad (foam or inflatable)',
        'Tent or bivy shelter (poles and stakes in a separate pouch)',
        'Camp stove, fuel canister, and lighter',
        'Lightweight cookpot and folding spoon/spork',
        'All meals and snacks for the trip (plus one emergency day of food)',
        'Water filter or purification tablets',
        'Water containers (minimum 2 L total capacity)',
        'Base layer + mid-layer clothing changes',
        'Waterproof jacket and waterproof pants',
        'First aid kit with blister care and personal medications',
        'Headlamp with spare batteries',
        'Navigation tools (map, compass, GPS)',
        'Toilet trowel and biodegradable soap (pack-out waste bags)',
        'Emergency whistle and signalling mirror',
      ],
      niceToHaveItems: [
        'Camp chair or sit pad',
        'Dry bags to protect electronics and sleeping bag',
        'Lightweight camp shoes or sandals',
        'Solar lantern or string lights',
        'Trekking poles',
        'Journaling notebook and pen',
        'Binoculars',
      ],
      buyingTips: [
        'Look for a top-loading pack with a floating lid — the lid pocket gives quick access to frequently needed items.',
        'An internal frame distributes weight far better than a frameless design for loads over 8 kg.',
        'Hip belt padded pockets are extremely useful for carrying snacks, phone, and sunscreen without stopping.',
        'Check that the torso length is adjustable — this is the most critical fit dimension for back comfort.',
        'Side compression straps allow you to cinch down a partially loaded pack, preventing gear from shifting.',
      ],
      careTips: [
        'Pack your shelter and sleeping bag in dry bags even if the pack has a built-in rain cover — condensation happens inside.',
        'Wash hip belt foam pads with warm water and soap after muddy trips — sweat-saturated foam breaks down quickly.',
        'Store the pack hanging or loosely stuffed; never store it compressed as this permanently deforms the foam padding.',
        'Inspect all strap attachment points and buckle clips each trip — replace buckles before they fail in the field.',
        'Re-apply DWR spray treatment to the outer fabric annually or when you notice water no longer beading on the surface.',
      ],
    ),
    EquipmentGuide(
      id: 'bp_multiday_guide',
      subCategoryId: 'bp_multiday',
      title: 'Multi-Day Pack Packing Guide',
      description:
          'A 50–70 L multi-day pack is designed for 3–7 day wilderness expeditions where you carry a full camp setup. '
          'Weight distribution and smart packing become critical at this volume — heavier items close to your spine, '
          'lighter items at the bottom and top.',
      essentialItems: [
        '4-season sleeping bag (rated for expected temperature range)',
        'Inflatable sleeping pad with repair kit',
        'Freestanding tent with footprint/groundsheet',
        'Camp stove and sufficient fuel for the trip duration',
        'Full cookset (pot, pan, cup, cutlery)',
        'Bear canister or bear hang kit for food storage',
        'All meals + 2 emergency ration days',
        'Water filter, backup purification tablets, 2+ litre capacity',
        'Complete change of clothes for each day (use merino wool to reduce volume)',
        'Hardshell rain jacket and waterproof pants',
        'Gaiters for stream crossings and wet terrain',
        'First aid kit with wilderness medicine supplies',
        'SAT communicator or PLB (personal locator beacon)',
        'Detailed topographic maps and compass',
        'Blister kit and anti-chafe products',
        'Lightweight camp shoes (Crocs or similar)',
      ],
      niceToHaveItems: [
        'Solar charging panel for electronics',
        'Inflatable pillow',
        'Hanging camp kitchen organiser',
        'Trekking poles with snow baskets',
        'Packable camp towel',
        'Lightweight book or e-reader',
        'Insulated mug for hot drinks',
      ],
      buyingTips: [
        'Prioritise a robust internal frame system (stay rods or an HDPE framesheet) — it is essential for loads over 12 kg.',
        'Look for a pack with a separate sleeping bag compartment at the base — this keeps the bottom organised and accessible.',
        'Front panel access (J-zip or U-zip) is a major quality-of-life upgrade for multi-day trips when you need mid-pack items.',
        'Fit the pack with at least 12 kg of weight before buying — the true comfort of the hip belt and shoulder straps only shows under load.',
        'Ice axe loops, crampon attachment points, and trekking pole loops are worth having if you hike mountainous terrain.',
      ],
      careTips: [
        'After river crossings, dry the pack frame and hip belt completely before storing — moisture can corrode metal stays.',
        'Remove the framesheet and clean the internal frame channel annually to remove sand and grit that abrades the material.',
        'Wax all external metal hardware (buckle pins, D-rings) lightly with Nikwax or similar to prevent surface rust.',
        'Re-waterproof any heat-taped seams that show delamination using seam sealer before they allow moisture ingress.',
        'Pack heavy items (tent, food, water) in the middle zone close to your spine — misbalanced loads cause back injury on long trips.',
      ],
    ),
    EquipmentGuide(
      id: 'bp_expedition_guide',
      subCategoryId: 'bp_expedition',
      title: 'Expedition Pack Packing Guide',
      description:
          'Packs of 70 L and above are for high-altitude mountaineering, polar expeditions, and very long wilderness routes. '
          'These packs are built for extreme loads and extreme weather. Systematic packing discipline is crucial — '
          'you will live out of this pack for weeks.',
      essentialItems: [
        'Expedition-grade 4-season tent rated for extreme wind and snow load',
        'Sub-zero sleeping bag (-20°C or below for high altitude)',
        'Insulated sleeping pad (R-value 5+)',
        'Mountaineering stove system (remote canister or liquid fuel) + fuel for full duration',
        'Full cook and melt-snow system',
        'Enough food for planned duration + 5-day emergency ration',
        'Complete mountaineering safety hardware (harness, carabiners, ice axe, crampons)',
        'Avalanche safety kit (beacon, probe, shovel)',
        'PLB with registered subscription',
        'Satellite communicator',
        'All extreme weather layers (base, mid, heavyweight insulation, hardshell)',
        'High-altitude first aid kit with altitude sickness medication',
        'Repair kit for tent, stove, pack, and footwear',
        'Detailed expedition maps + backup compass',
        'Glacier glasses and goggles',
      ],
      niceToHaveItems: [
        'Down camp booties',
        'Expedition gaiters',
        'Expedition-grade ski poles',
        'Snow stakes for tent anchoring',
        'Hand and toe warmers (chemical)',
        'Camera with weather-sealed body',
        'Lightweight journaling set',
      ],
      buyingTips: [
        'Full perimeter framesheet and dual aluminium stay system are non-negotiable for consistent 20+ kg loads.',
        'Look for dual access (top + front panel) and a removable summit pack feature for approach camps.',
        'Wide, well-padded hip wings are essential — 70–80% of pack weight should ride on your hips, not your shoulders.',
        'Haul loops, rope management straps, and ice axe loops should be bomber-grade hardware, not sewn fabric loops.',
        'Test the pack in the most challenging conditions you can access before the expedition — you need to know its failure modes.',
      ],
      careTips: [
        'Completely dry and clean the pack between expedition legs — high humidity inside stores destroys foam padding and coatings.',
        'Inspect every single stitching point, bartack, and webbing anchor after a major expedition.',
        'Professional pack repair by a gear repair shop is always worth it — never field-repair a structural failure with duct tape permanently.',
        'Store the pack hanging, loosely stuffed, in a cool dry location away from direct sunlight (UV degrades all fabrics over time).',
        'Document and replace all consumable components (buckle pins, zipper sliders) that show wear before the next trip.',
      ],
    ),
    EquipmentGuide(
      id: 'bp_hydration_guide',
      subCategoryId: 'bp_hydration',
      title: 'Hydration Pack Guide',
      description:
          'Hydration packs (2–12 L) integrate a water reservoir (bladder) with a drinking tube for hands-free hydration. '
          'They are ideal for trail running, mountain biking, and short but intense hikes where carrying poles '
          'or stopping to drink from a bottle is impractical.',
      essentialItems: [
        'Hydration reservoir (2–3 L bladder with secure screw or slide-lock cap)',
        'Bite valve cover (keeps the mouthpiece clean when not in use)',
        'High-energy snacks for your activity duration',
        'Mobile phone in a zippered pocket',
        'Emergency whistle',
        'Compact first aid items (bandages, blister pads)',
        'Lightweight windbreaker or packable shell',
        'Trail identification (ID card)',
      ],
      niceToHaveItems: [
        'Insulated tube cover (keeps water cool in summer, prevents freezing in winter)',
        'Spare bite valve',
        'Portable power bank for GPS watch',
        'Foldable trekking poles',
        'Small action camera mount',
        'High-SPF lip balm and sunscreen stick',
      ],
      buyingTips: [
        'Choose a wide-mouth reservoir for easy cleaning and ice-cube filling — narrow-mouth reservoirs trap mold.',
        'Look for a low centre of gravity panel (reservoir sits close to your back) to avoid the sloshing shift that affects running balance.',
        'A magnetic tube clip keeps the mouthpiece accessible at all times without removing the pack.',
        'If using in winter, choose a pack with an insulated tube sleeve or purchase one separately.',
        'Minimum 2 L reservoir for any activity exceeding 1 hour in warm weather — 3 L for longer or more intense activities.',
      ],
      careTips: [
        'Rinse the reservoir and tube with warm water and reservoir-specific cleaning tablets after every single use.',
        'Dry the bladder completely before storage — hang it inverted with a paper towel inside to absorb moisture.',
        'Freeze the reservoir if long-term storage is needed — this prevents mold growth effectively.',
        'Replace the bite valve annually (or sooner if discoloured or the one-way valve becomes stiff).',
        'Check the tube for kinks and the clamp connection for cracks after every washing — these are common failure points.',
      ],
    ),
    EquipmentGuide(
      id: 'bp_kids_guide',
      subCategoryId: 'bp_kids',
      title: "Children's Pack Guide",
      description:
          "A well-fitted children's pack makes young hikers feel capable and independent. "
          'Pack weight for children should never exceed 10–15% of body weight. '
          'The right fit, fun colours, and just the right amount of responsibility make all the difference '
          'in getting children excited about the outdoors.',
      essentialItems: [
        "Child's water bottle (at least 500 ml, insulated recommended)",
        'Trail snacks (nut butter pouches, fruit leather, crackers)',
        'Light rain jacket in an accessible outer pocket',
        "Spare warm layer (fleece, since children's core temperature drops faster than adults)",
        'Small personal first aid items (plasters, blister pads)',
        'Emergency whistle clipped externally',
        'Small headlamp with fresh batteries',
        'Sunscreen and lip balm',
        'A favourite small comfort item (boosts morale on tough sections)',
      ],
      niceToHaveItems: [
        'Lightweight magnifying glass (great for nature exploration)',
        'Small field guide to local birds or plants',
        'Compact binoculars (light ones sized for children)',
        'Small camera or kids-proof action camera',
        'Nature journal and coloured pencils',
        'Lightweight sit pad',
      ],
      buyingTips: [
        "Buy a pack with a torso-length adjustment — children grow fast and a pack that fits ages 6–10 avoids frequent replacements.",
        'A sternum strap at a child-appropriate height keeps the pack from swaying and helps shoulder straps stay in place.',
        'Chest and hip belt padding should be proportional — children with small waists need narrow, soft hip belts.',
        'Bright colours and fun designs genuinely increase enthusiasm in younger children — factor in their preference when choosing.',
        'Start with the pack carrying only water and a snack — increase contents gradually as the child builds strength and confidence.',
      ],
      careTips: [
        'Check for food crumbs, wrappers, and wet clothing after every trip — leftover food in a pack attracts insects and mildew.',
        'Wash the pack according to the care label at the end of each season, or immediately after a muddy trip.',
        'Check that all buckles and clips still function correctly before each trip — children are harder on gear than adults.',
        'Inspect the bottom of the pack for abrasion wear — children often drag or drop their packs on rough terrain.',
        "Reassess fit at the start of each season — children's torso lengths change significantly over 6–12 months.",
      ],
    ),
  ];
}
